// type = "module"
const countryList = [
    'China',
    'India',
    'United States',
    "Indonesia",
    "Pakistan",
    "Brazil",
    "Nigeria",
    "Bangladesh",
    "Russia",
    "Mexico",
    "Japan",
    "Ethiopia",
    "Philippines",
    "Egypt",
    "Vietnam",
    "Turkey",
    "Iran",
    "Germany",
    "Thailand",
    "United Kingdom",
    "France",
    "Italy",
    "Tanzania",
    "South Africa",
    "Myanmar",
    "Kenya",
    "South Korea",
    "Colombia",
    "Spain",
    "Uganda",
    "Argentina",
    "Algeria",
    "Sudan",
    "Ukraine",
    "Iraq",
    "Afghanistan",
    "Poland",
    "Canada",
    "Morocco",
    "Saudi Arabia",
    "Uzbekistan",
    "Peru",
    "Angola",
    "Malaysia",
    "Mozambique",
    "Ghana",
    "Yemen",
    "Nepal",
    "Venezuela",
    "Madagascar",
    "Cameroon",
    "Côte d'Ivoire",
    "North Korea",
    "Australia",
    "Niger",
    "Taiwan",
    "Sri Lanka",
    "Mali",
    "Romania",
    "Malawi",
    "Chile",
    "Kazakhstan",
    "Zambia",
    "Guatemala",
    "Ecuador",
    "Syria",
    "Netherlands",
    "Senegal",
    "Cambodia",
    "Chad",
    "Somalia",
    "Zimbabwe",
    "Guinea",
    "Rwanda",
    "Tunisia",
    "Bolivia",
    "Belgium",
    "Haiti",
    "Cuba",
    "South Sudan",
    "Dominican Republic",
    "Czech Republic",
    "Greece",
    "Jordan",
    "Portugal",
    "Azerbaijan",
    "Sweden",
    "Honduras",
    "United Arab Emirates",
    "Hungary",
    "Tajikistan",
    "Belarus",
    "Austria",
    "Papua New Guinea",
    "Serbia",
    "Israel",
    "Switzerland",
    "Sierra Leone",
    "Hong Kong",
    "Laos",
    "Paraguay",
    "Bulgaria",
    "Libya",
    "Lebanon",
    "Nicaragua",
    "Kyrgyzstan",
    "El Salvador",
    "Turkmenistan",
    "Singapore",
    "Denmark",
    "Finland",
    "Congo",
    "Slovakia",
    "Norway",
    "Oman",
    "Palestine",
    "Costa Rica",
    "Liberia",
    "Ireland",
    "New Zealand",
    "Panama",
    "Kuwait",
    "Croatia",
    "Georgia",
    "Eritrea",
    "Uruguay",
    "Bosnia and Herzegovina",
    "Mongolia",
    "Armenia",
    "Jamaica",
    "Qatar",
    "Albania",
    "Puerto Rico",
    "Lithuania",
    "Gambia",
    "Botswana",
    "Gabon",
    "Lesotho",
    "Slovenia",
    "Equatorial Guinea",
    "Trinidad and Tobago",
    "Estonia",
    "Fiji",
    "Guyana",
    "Montenegro",
    "Luxembourg",
    "Suriname",
    "Maldives",
    "Belize",
    "Bahamas",
    "Iceland",
    "French Guiana",
    "Barbados",
    "Antigua and Barbuda",
    "Andorra",
    "Dominica",
    "Greenland",
    "Monaco",
    "Liechtenstein",
    'Democratic Republic of the Congo'
];

export default countryList 